<a href="https://colab.research.google.com/github/Bhanugt/IBD-Classification-and-prediction/blob/main/LogisticModel_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Apply Label Encoding for categorical columns
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le  # Store encoders for inverse transformation if needed

print("✅ Categorical Data Converted to Numeric Format!")


✅ Categorical Data Converted to Numeric Format!


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load dataset
df = pd.read_csv("/content/sample_data/synthetic_ibd_dataset.csv")

# Convert categorical values to numeric using Label Encoding
categorical_cols = df.select_dtypes(include=['object']).columns
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Define features (X) and target (y)
X = df.drop(columns=["IBD_Type"])  # Modify "IBD_Type" to match your dataset
y = df["IBD_Type"]

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert target variable to integer labels (if needed)
y = y.astype(int)

# Split dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("✅ Data Loaded & Preprocessed Successfully!")


✅ Data Loaded & Preprocessed Successfully!


In [ ]:
# Define hyperparameter grid
param_grid = {
    "C": [0.01, 0.1, 1, 10, 100],
    "solver": ["liblinear"],  # Supports L1 and L2 penalty
    "penalty": ["l1", "l2"]
}

# Apply GridSearchCV for best parameters
grid_search = GridSearchCV(LogisticRegression(max_iter=3000), param_grid, cv=10, scoring="accuracy", n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

# Get the best model
best_lr = grid_search.best_estimator_

print("🔥 Best Hyperparameters:", grid_search.best_params_)


Fitting 10 folds for each of 10 candidates, totalling 100 fits
🔥 Best Hyperparameters: {'C': 0.01, 'penalty': 'l1', 'solver': 'liblinear'}


In [ ]:
# Make predictions on test data
y_pred = best_lr.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("✅ Logistic Regression Accuracy:", round(accuracy * 100, 2), "%")

# Print Confusion Matrix
print("📊 Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Print Classification Report
print("📄 Classification Report:\n", classification_report(y_test, y_pred))


✅ Logistic Regression Accuracy: 27.0 %
📊 Confusion Matrix:
 [[27  0  0]
 [33  0  0]
 [40  0  0]]
📄 Classification Report:
               precision    recall  f1-score   support

           0       0.27      1.00      0.43        27
           1       0.00      0.00      0.00        33
           2       0.00      0.00      0.00        40

    accuracy                           0.27       100
   macro avg       0.09      0.33      0.14       100
weighted avg       0.07      0.27      0.11       100



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# Save the trained Logistic Regression model
joblib.dump(best_lr, "logistic_regression_model.pkl")

print("✅ Model saved as 'logistic_regression_model.pkl'!")


✅ Model saved as 'logistic_regression_model.pkl'!
